# Generated by Django 4.2.13 on 2024-06-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(choices=[('dokument', 'Dokument'), ('länk', 'Länk')], default='none', help_text='Välj om du vill lägga upp ett dokument eller en länk.')),
                ('name', models.CharField(help_text='Skriv vad det är för dokumentet eller länk.', max_length=200)),
                ('url', models.TextField(help_text='Klistra in URL/länken till dokumentet eller önskad länk här.', max_length=1000)),
            ],
        ),
    ]
