# Generated by Django 4.2.13 on 2024-06-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.TextField(help_text='Klistra in URL/länken till dokumentet eller önskad länk.', max_length=1000),
        ),
    ]
