# Generated by Django 4.2.13 on 2024-06-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_document_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(help_text='Skriv förnamn för personen.', max_length=200)),
                ('lname', models.CharField(help_text='Skriv efternamn för personen.', max_length=200)),
                ('department', models.CharField(help_text='Skriv arbetsområde för personen.', max_length=200)),
                ('email', models.CharField(help_text='Skriv en e-postadress för personen.', max_length=254)),
            ],
        ),
    ]
