# Generated by Django 4.2.13 on 2024-06-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff Member'},
        ),
    ]
